/**
 * The reviewed allowlist of database objects the `anon` role can reach.
 *
 * WHAT THIS IS
 *   A committed record of exactly what the public anon key can touch in the
 *   `public` schema of the BingoBlast project, as reviewed by a human. Every
 *   entry below was read from the live catalogue, checked against what the app
 *   actually needs, and kept deliberately.
 *
 *   `tests/anon-access.test.ts` reads the live catalogue and fails when the
 *   database grants anon anything this file does not list, or grants more on a
 *   listed object than this file allows. The test skips with an explanation when
 *   no database connection is configured, so it is inert by default and only
 *   speaks when pointed at a real project.
 *
 * WHY IT EXISTS
 *   Anon reach in this project has drifted twice before, silently and on every
 *   build. On 30 July 2026 the four host RPCs were found anon-callable
 *   (`call_next_number`, `void_last_number`, `record_winner_atomic`,
 *   `assert_is_host`), repaired by 20260730070705, and then found to be
 *   recreated anon-callable on every fresh build until 5f4755d folded the revoke
 *   into the migration that creates them. Three migrations that production had
 *   applied were missing from this repository entirely and had to be recovered
 *   from `supabase_migrations.schema_migrations.statements`.
 *
 *   The cause is still armed. `pg_default_acl` on this project grants anon
 *   EXECUTE on every new function in `public`, and every table privilege on
 *   every new table, so the next `create function` picks anon straight back up
 *   with nobody having written a grant. `supabase/tests/convention-gap.test.sql`
 *   reproduces that in a container. No migration in this repository revokes
 *   those default privileges, so this allowlist is the detection that stands in
 *   for a fix that has not been made.
 *
 *   This app moves money: snowball jackpots, prize amounts and tie shares. Anon
 *   reach is not a theoretical concern here.
 *
 * WHAT MUST NEVER APPEAR IN THIS FILE
 *   No money-moving function and no host-only or admin-only function may ever be
 *   added to `ANON_ALLOWLIST`. Those are listed by name in `NEVER_ALLOWLIST`
 *   below and the test enforces it, so a careless edit to this file fails rather
 *   than passing quietly. They are reachable only by an authenticated host or
 *   admin, through `assert_is_host()` or `assert_is_admin()`, and a grant to
 *   anon on any of them is an incident, not a configuration choice. If one of
 *   them shows up in the live catalogue, the fix is a migration that revokes it,
 *   never an edit to this file.
 *
 * HOW TO UPDATE IT, DELIBERATELY
 *   1. Do not edit this file to make a failing test pass. A failure means the
 *      live database changed. Find out which migration changed it first.
 *   2. If the new reach is wanted, add the entry with a `why` that says which
 *      feature needs it and which migration granted it, in the same pull request
 *      as that migration.
 *   3. If the new reach is not wanted, write a migration that revokes it. The
 *      shape that actually closes it is both revokes together, because
 *      `create function` grants PUBLIC its own EXECUTE and anon is a member of
 *      PUBLIC: `revoke execute on function ... from public, anon;`
 *   4. Re-run `npx tsx --test tests/anon-access.test.ts` with `SUPABASE_DB_URL`
 *      set, and paste the result into the pull request.
 *
 * A NOTE ON THE TABLE ENTRIES
 *   Anon holds every table privilege on every table in `public`. That is not a
 *   decision anyone here made: it is what Supabase's default privileges grant,
 *   and removing it project-wide is a change with real blast radius. RLS is
 *   therefore the control, and every table below carries RLS with policies. The
 *   `why` on each entry records what RLS actually lets anon do, checked against
 *   the live REST API with the public anon key on 4 September 2026, not inferred
 *   from the policy text. The value of listing them is that a NEW table appears
 *   here as a failure the day it is created, while it is still empty.
 *
 * EVIDENCE
 *   Read from project bcmorqsgeumtmhvctvgu (BingoBlast) on 4 September 2026,
 *   read-only. Nothing was granted, revoked or migrated to produce it.
 */

export type AnonObjectKind =
  | 'table'
  | 'view'
  | 'materialized view'
  | 'sequence'
  | 'function';

/** One object the live catalogue says anon can reach. */
export interface AnonCatalogueEntry {
  kind: AnonObjectKind;
  /** Tables, views and sequences use the bare relation name. Functions use
   *  `name(identity arguments)`, so an overload cannot hide behind its sibling. */
  name: string;
  privileges: string[];
}

export interface AnonAllowlistEntry extends AnonCatalogueEntry {
  why: string;
}

/**
 * Every table privilege Postgres 17 can grant. MAINTAIN is 17 only, so the
 * catalogue query below asks for it only when the server is new enough.
 */
export const TABLE_PRIVILEGES = [
  'SELECT',
  'INSERT',
  'UPDATE',
  'DELETE',
  'TRUNCATE',
  'REFERENCES',
  'TRIGGER',
] as const;

export const TABLE_PRIVILEGES_PG17 = [...TABLE_PRIVILEGES, 'MAINTAIN'] as const;

export const SEQUENCE_PRIVILEGES = ['SELECT', 'UPDATE', 'USAGE'] as const;

/** What Supabase's default privileges hand anon on every table in `public`. */
const SUPABASE_DEFAULT_TABLE_GRANT = [
  'DELETE',
  'INSERT',
  'MAINTAIN',
  'REFERENCES',
  'SELECT',
  'TRIGGER',
  'TRUNCATE',
  'UPDATE',
];

/**
 * The reviewed set. Anything the live catalogue reports that is not here fails
 * the test, and so does anything here that the live catalogue reports with more
 * privileges than listed.
 */
export const ANON_ALLOWLIST: readonly AnonAllowlistEntry[] = [
  {
    kind: 'table',
    name: 'game_states',
    privileges: SUPABASE_DEFAULT_TABLE_GRANT,
    why: 'Grant is the Supabase default; RLS is the control. Every policy requires a profiles row for auth.uid(), so anon reads zero rows. Verified: the REST API returns an empty array to the anon key. The host and display pages read the public mirror instead.',
  },
  {
    kind: 'table',
    name: 'game_states_public',
    privileges: SUPABASE_DEFAULT_TABLE_GRANT,
    why: 'Deliberately public. This is the trigger-synced mirror the pub TV at /display and the phone follower at /player subscribe to over Realtime, both of which are unauthenticated by design. Its SELECT policy is USING (true). It carries no player-identifying data and no money.',
  },
  {
    kind: 'table',
    name: 'games',
    privileges: SUPABASE_DEFAULT_TABLE_GRANT,
    why: 'Readable by anon: SELECT policy is USING (true). The display and player pages need the game list, names, colours and stage sequence without signing in. Note this also exposes the prizes and notes columns to anyone with the anon key.',
  },
  {
    kind: 'table',
    name: 'profiles',
    privileges: SUPABASE_DEFAULT_TABLE_GRANT,
    why: 'Grant is the Supabase default; RLS is the control. SELECT is scoped to the authenticated role, and the INSERT policy requires auth.uid() = id with role pending, which anon cannot satisfy. Verified: the REST API returns an empty array to the anon key. Staff identities stay closed.',
  },
  {
    kind: 'table',
    name: 'session_reset_log',
    privileges: SUPABASE_DEFAULT_TABLE_GRANT,
    why: 'Grant is the Supabase default; RLS is the control. The only policy is admin SELECT. Verified: the REST API returns an empty array to the anon key.',
  },
  {
    kind: 'table',
    name: 'sessions',
    privileges: SUPABASE_DEFAULT_TABLE_GRANT,
    why: 'Readable by anon: SELECT policy is USING (true). The display root has to find the one ready or running session before anyone signs in, and /player resolves a session from a QR link. Note this also exposes the notes column to anyone with the anon key.',
  },
  {
    kind: 'table',
    name: 'snowball_pot_history',
    privileges: SUPABASE_DEFAULT_TABLE_GRANT,
    why: 'Grant is the Supabase default; RLS is the control. Both policies are admin only, which is the money boundary this app is built around. Verified: the REST API returns an empty array to the anon key.',
  },
  {
    kind: 'table',
    name: 'snowball_pots',
    privileges: SUPABASE_DEFAULT_TABLE_GRANT,
    why: 'Readable by anon, deliberately and narrowly: the SELECT policy names auth.role() = anon explicitly so the pub TV can show the jackpot and the call target without signing in. It exposes current_jackpot_amount, base_jackpot_amount and the increments, which are money values, but they are the same numbers printed on the board in the room. Writes are admin only. If the display ever stops needing this, the policy should be narrowed rather than left open.',
  },
  {
    kind: 'table',
    name: 'winners',
    privileges: SUPABASE_DEFAULT_TABLE_GRANT,
    why: 'Grant is the Supabase default; RLS is the control. Closed to anon by 20260825080607_winners_not_publicly_readable; SELECT is staff only and UPDATE is admin only. Verified: the REST API returns an empty array to the anon key. Inserts happen only through record_winner_atomic.',
  },
];

/**
 * Function and trigger-function names that must never be added to
 * `ANON_ALLOWLIST`, whatever the live catalogue says. These move money, decide
 * who won, or gate the host and admin boundary. The test asserts the allowlist
 * contains none of them, so this rule is enforced rather than merely written
 * down.
 */
export const NEVER_ALLOWLIST: readonly string[] = [
  // The host and admin gate itself.
  'assert_is_admin',
  'assert_is_host',
  // Number calling and winner recording.
  'call_next_number',
  'record_winner_atomic',
  'void_last_number',
  // Money: pots, prizes and shares.
  'archive_snowball_pot',
  'parse_prize_pence',
  'recompute_prize_shares',
  'reset_snowball_pot_safe',
  'set_winner_prize_given',
  'settle_snowball_pot',
  'update_snowball_pot_safe',
  // Admin session and game management, including destructive operations.
  'delete_game_safe',
  'delete_session_safe',
  'reset_session_safe',
  'update_game_safe',
  // Trigger functions. Nothing should call these directly, least of all anon.
  'bump_game_state_version',
  'handle_new_user',
  'sync_game_states_public',
  'sync_prize_shares',
  // Not this app's function at all. See ANON_OPEN_ITEMS.
  'create_table_booking_transaction',
];

/**
 * Anon reach that has been reviewed, is NOT approved, and has not been closed
 * yet. Listing it here does not allow it: the test still fails on it. The point
 * is that the failure reads as a known open item with a decision attached rather
 * than as a fresh regression, and that it stays visible until it is dealt with.
 */
export interface AnonOpenItem {
  kind: AnonObjectKind;
  name: string;
  why: string;
}

export const ANON_OPEN_ITEMS: readonly AnonOpenItem[] = [
  {
    kind: 'function',
    name: 'create_table_booking_transaction(p_booking_data jsonb, p_menu_items jsonb, p_payment_data jsonb)',
    why: [
      'A SECURITY DEFINER function that belongs to no code in this repository.',
      'It writes table_bookings, table_booking_items and table_booking_payments,',
      'none of which exist in this database, and it is executable by anon through',
      'both an explicit anon grant and a PUBLIC grant. It reaches its own body when',
      'called with the public anon key and fails only on the missing table, so the',
      'grant is live rather than theoretical. It appears in no migration here; it',
      'was recovered as an ALTER target by 20260527063058 and deliberately left',
      'alone by 20260730070705 because revoking a grant whose callers are unknown',
      'is how outages happen. Tracked as sec-orphan-booking-function in',
      'tasks/2026-08-25-end-to-end-review, R1-before-release, where the recommended',
      'action is to revoke PUBLIC and anon now and drop the function once somebody',
      'confirms nothing else calls it. That decision is still open.',
    ].join(' '),
  },
];

/**
 * The catalogue query the test runs against the live database. Read-only.
 *
 * It asks `has_*_privilege` rather than reading ACL arrays, because that is the
 * question worth answering: what anon can actually do, including anything it
 * inherits through PUBLIC. Functions are keyed by identity arguments so an
 * overload cannot hide behind a sibling with the same name, which is the exact
 * shape the July 2026 drift took.
 */
export const ANON_CATALOGUE_QUERY = `
with table_privs as (
  select case when current_setting('server_version_num')::int >= 170000
              then array[${TABLE_PRIVILEGES_PG17.map((p) => `'${p}'`).join(',')}]
              else array[${TABLE_PRIVILEGES.map((p) => `'${p}'`).join(',')}] end as names
),
rel as (
  select case c.relkind when 'r' then 'table' when 'p' then 'table'
                        when 'v' then 'view' when 'm' then 'materialized view' end as kind,
         c.relname as name,
         (select coalesce(array_agg(p order by p), array[]::text[])
            from table_privs, unnest(table_privs.names) p
           where has_table_privilege('anon', c.oid, p)) as privileges
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
   where n.nspname = 'public' and c.relkind in ('r','p','v','m')
),
seq as (
  select 'sequence' as kind, c.relname as name,
         (select coalesce(array_agg(p order by p), array[]::text[])
            from unnest(array[${SEQUENCE_PRIVILEGES.map((p) => `'${p}'`).join(',')}]) p
           where has_sequence_privilege('anon', c.oid, p)) as privileges
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
   where n.nspname = 'public' and c.relkind = 'S'
),
fn as (
  select 'function' as kind,
         p.proname || '(' || pg_get_function_identity_arguments(p.oid) || ')' as name,
         array['EXECUTE'] as privileges
    from pg_proc p
   where p.pronamespace = 'public'::regnamespace
     and has_function_privilege('anon', p.oid, 'EXECUTE')
)
select coalesce(json_agg(row_to_json(x) order by x.kind, x.name), '[]'::json) as reachable
  from (
    select * from rel where cardinality(privileges) > 0
    union all select * from seq where cardinality(privileges) > 0
    union all select * from fn
  ) x;
`.trim();

/** One way the live database is wider than the allowlist. */
export interface AnonAccessFinding {
  kind: AnonObjectKind;
  name: string;
  /** `unlisted` is an object anon can reach that the allowlist does not mention.
   *  `widened` is a listed object holding privileges beyond those allowed. */
  problem: 'unlisted' | 'widened';
  extraPrivileges: string[];
  /** Set when this object is a reviewed, still-open item rather than new drift. */
  knownOpenItem?: string;
}

export interface AnonAccessDiff {
  findings: AnonAccessFinding[];
  /** Allowlisted objects the live database no longer grants, or grants less of.
   *  Not a failure: the world got tighter. Reported so the file can be trimmed. */
  stale: string[];
}

const keyOf = (kind: string, name: string): string => `${kind} ${name}`;

/**
 * Compare a live catalogue reading against the allowlist. Pure, so the rules are
 * unit-tested without a database.
 */
export function diffAnonAccess(
  reachable: readonly AnonCatalogueEntry[],
  allowlist: readonly AnonAllowlistEntry[] = ANON_ALLOWLIST,
  openItems: readonly AnonOpenItem[] = ANON_OPEN_ITEMS,
): AnonAccessDiff {
  const allowed = new Map<string, AnonAllowlistEntry>(
    allowlist.map((entry) => [keyOf(entry.kind, entry.name), entry]),
  );
  const open = new Map<string, AnonOpenItem>(
    openItems.map((item) => [keyOf(item.kind, item.name), item]),
  );

  const findings: AnonAccessFinding[] = [];
  const seen = new Set<string>();

  for (const entry of reachable) {
    const key = keyOf(entry.kind, entry.name);
    seen.add(key);
    const allowedEntry = allowed.get(key);

    if (!allowedEntry) {
      findings.push({
        kind: entry.kind,
        name: entry.name,
        problem: 'unlisted',
        extraPrivileges: [...entry.privileges].sort(),
        ...(open.has(key) ? { knownOpenItem: open.get(key)!.why } : {}),
      });
      continue;
    }

    const permitted = new Set(allowedEntry.privileges);
    const extra = entry.privileges.filter((p) => !permitted.has(p)).sort();
    if (extra.length > 0) {
      findings.push({
        kind: entry.kind,
        name: entry.name,
        problem: 'widened',
        extraPrivileges: extra,
      });
    }
  }

  const stale = [...allowed.keys()].filter((key) => !seen.has(key)).sort();

  return { findings, stale };
}

/** A failure message that names the objects and says what to do about them. */
export function describeAnonAccessFindings(
  findings: readonly AnonAccessFinding[],
): string {
  const lines = [
    `anon can reach ${findings.length} object(s) that supabase/anon-access-allowlist.ts does not allow.`,
    '',
  ];

  for (const finding of findings) {
    if (finding.problem === 'unlisted') {
      lines.push(
        `  NOT ALLOWLISTED  ${finding.kind} ${finding.name}`,
        `                   anon holds: ${finding.extraPrivileges.join(', ')}`,
      );
      if (finding.knownOpenItem) {
        lines.push(
          '                   This is a reviewed, still-open item, not new drift:',
          `                   ${finding.knownOpenItem}`,
        );
      }
    } else {
      lines.push(
        `  WIDENED          ${finding.kind} ${finding.name}`,
        `                   anon gained: ${finding.extraPrivileges.join(', ')}`,
      );
    }
    lines.push('');
  }

  lines.push(
    'Do not edit the allowlist to make this pass. Find the migration that changed',
    'the database. If the reach is wanted, add it to the allowlist with a reason in',
    'the same pull request. If it is not, write a migration that revokes it, from',
    'PUBLIC and anon together, because create function grants PUBLIC its own EXECUTE',
    'and anon is a member of PUBLIC.',
  );

  return lines.join('\n');
}
