-- New accounts land inert instead of landing as staff.
--
-- WHY
--   handle_new_user() inserted every new auth.users row into public.profiles
--   with role = 'host', and user_role had only {admin, host}, so there was no
--   unprivileged tier for an account to land in. Combined with self-signup being
--   enabled on the project (verified 2026-08-25: GET /auth/v1/settings returned
--   disable_signup false), anyone who could read the public anon key off the
--   /display or /player page could sign up, confirm their own email, and hold a
--   host account: enough to call balls, void balls, record winners and move the
--   snowball pot on a live game.
--
--   The app's own signup() server action returns "Registration is invite-only",
--   but that is decoration. It does not touch GoTrue's /auth/v1/signup endpoint,
--   which is public unless the project setting says otherwise.
--
-- THIS IS ONE OF TWO FIXES, AND IT IS THE ONE THAT LASTS
--   The other is turning "Allow new users to sign up" off in the Supabase
--   dashboard. That is the emergency stop and it must be done, but it is an
--   untracked hosted setting that can drift back. This migration is the part
--   that holds regardless: even with signup on, a new account is inert until an
--   admin deliberately promotes it.
--
-- SAFETY FOR EXISTING ROWS
--   Nothing is backfilled. Production holds exactly one profile, role 'admin'
--   (verified 2026-08-25), and any real host account created between now and
--   this migration is left exactly as it is. Only accounts created AFTER this
--   runs are affected.
--
-- WHY THIS MIGRATION CONTAINS ONE STATEMENT
--   Postgres refuses to USE a new enum value in the same transaction that adds
--   it, and `supabase db push` wraps each migration file in a transaction. This
--   file originally also set the column default to 'pending' and replaced
--   handle_new_user, and production rejected it:
--
--     ERROR: unsafe use of new value "pending" of enum type user_role (55P04)
--     At statement: alter table public.profiles alter column role set default ...
--
--   The whole migration rolled back, so nothing was half applied. But it did not
--   fail locally, because psql runs a file statement by statement in autocommit
--   while db push does not, which is a fidelity gap now closed in
--   supabase/tests/run.sh by replaying each migration with --single-transaction.
--
--   So the value is added here, alone, and everything that USES it lives in
--   20260825080611_pending_role_default_and_trigger.sql. Do not merge them back
--   together, and do not add a backfill that writes 'pending' to this file.
--
-- APPLICATION COMPATIBILITY
--   Deploy the app first, or together. src/utils/supabase/middleware.ts must
--   already require an explicit admin or host role before this runs, otherwise a
--   pending account could reach /host and be refused only by RLS, which would
--   look like a broken screen rather than a refusal. The /pending page is the
--   destination for such an account.

alter type public.user_role add value if not exists 'pending';
